In [1]:
import pandas as pd
import numpy as np
import blinksear as ear
import blinksdistance as distance
import blinkscolors as colors
import json
import matplotlib.pyplot as plt
from pathlib import Path

from blinksear import isBlinkByEar
from blinksear import isBlinkByEar1
from blinksear import isBlinkByEar2
from blinksdistance import BlinkDistance
from blinkscolors import Colors
from blinkscorrelation import Correlation

In [2]:
def generate_webgazer_dataframe(df):
    df1 = df[df["trial_type"] == "html-keyboard-response"]
    df_webgazer = df1[~df1["webgazer_data"].isna()]
    dfs = []
    for row in range(len(df_webgazer)):
        json_data = df_webgazer["webgazer_data"].iloc[row].replace("'", "\"")
        data_list = json.loads(json_data)
        df_tmp = pd.DataFrame(data_list)
        df_tmp["trial"] = row + 1
        dfs.append(df_tmp)
    return pd.concat(dfs)

In [3]:
# This can load all data but is not storing df_webgazer in any place
files = Path("./data/all-exp-separados/").glob("*.csv")
dfs = []
i = 0
for file in files:
    if "blink" in str(file):
        print(file)
        df = pd.read_csv(file)
        df_tmp = generate_webgazer_dataframe(df)
        print(len(df_tmp))
        df_tmp["experiment"] = i
        df_tmp["file_name"] = str(file)
        i+=1
        dfs.append(df_tmp)

df_webgazer = pd.concat(dfs)
print(len(df_webgazer))

data/all-exp-separados/dataframe_blink_22.csv
1944
data/all-exp-separados/dataframe_blink_9.csv
743
data/all-exp-separados/dataframe_blink_8.csv
1206
data/all-exp-separados/dataframe_blink_23.csv
1480
data/all-exp-separados/dataframe_blink_21.csv
1974
data/all-exp-separados/dataframe_blink_20.csv
1584
data/all-exp-separados/dataframe_blink_18.csv
2598
data/all-exp-separados/dataframe_blink_24.csv
1894
data/all-exp-separados/dataframe_blink_25.csv
1843
data/all-exp-separados/dataframe_blink_19.csv
785
data/all-exp-separados/dataframe_blink_17.csv
490
data/all-exp-separados/dataframe_blink_1.csv
1417
data/all-exp-separados/dataframe_blink_16.csv
1558
data/all-exp-separados/dataframe_blink_14.csv
1476
data/all-exp-separados/dataframe_blink_3.csv
2880
data/all-exp-separados/dataframe_blink_2.csv
2361
data/all-exp-separados/dataframe_blink_15.csv
1937
data/all-exp-separados/dataframe_blink_11.csv
2162
data/all-exp-separados/dataframe_blink_6.csv
1343
data/all-exp-separados/dataframe_blink_7.csv
1543
data/all-exp-separados/dataframe_blink_10.csv
2403
data/all-exp-separados/dataframe_blink_12.csv
1594
data/all-exp-separados/dataframe_blink_5.csv
82
data/all-exp-separados/dataframe_blink_4.csv
1595
data/all-exp-separados/dataframe_blink_13.csv
1477
40369

In [4]:
blinkDistance = distance.BlinkDistance()
blinkColors = Colors()
blinkCorrelations = Correlation()


df_webgazer["isBlinkByEar"] = df_webgazer["importantKeypoints"].map(
    lambda x: isBlinkByEar(
        x["rightEyeTopArc"],
        x["rightEyeBottomArc"],
        x["leftEyeTopArc"],
        x["leftEyeBottomArc"],
    )
)
# df_webgazer['isBlinkByEar'] = df_webgazer['importantKeypoints'].map(lambda x: isBlinkByEar(x['rightEyeTopArc'], x['rightEyeBottomArc'], x['leftEyeTopArc'], x['leftEyeBottomArc']))

df_webgazer

,x,y,t,importantKeypoints,dz,trial,experiment,file_name,isBlinkByEar,isBlinkByDistance
0,0,0,6,"{'noseX': 299.44, 'noseY': 285.45, 'topY': 174...",59.37,1,0,data/all-exp-separados/dataframe_blink_22.csv,"[False, False, False, False, True, True, True,...","[False, False, False, False, False, False, Fal..."
1,0,0,40,"{'noseX': 299.86, 'noseY': 284.82, 'topY': 174...",56.06,1,0,data/all-exp-separados/dataframe_blink_22.csv,"[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False, Fal..."
2,0,0,74,"{'noseX': 300.63, 'noseY': 285.45, 'topY': 173...",53.35,1,0,data/all-exp-separados/dataframe_blink_22.csv,"[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False, Fal..."
3,0,0,106,"{'noseX': 301.08, 'noseY': 285.31, 'topY': 173...",51.42,1,0,data/all-exp-separados/dataframe_blink_22.csv,"[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False, Fal..."
4,0,0,141,"{'noseX': 301.66, 'noseY': 285.31, 'topY': 173...",50.71,1,0,data/all-exp-separados/dataframe_blink_22.csv,"[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False, Fal..."
...,...,...,...,...,...,...,...,...,...,...
251,0,0,8543,"{'noseX': 390, 'noseY': 299.17, 'topY': 162.47...",42.36,6,24,data/all-exp-separados/dataframe_blink_13.csv,"[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False, Fal..."
252,0,0,8578,"{'noseX': 386.91, 'noseY': 297.21, 'topY': 161...",43.42,6,24,data/all-exp-separados/dataframe_blink_13.csv,"[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False, Fal..."
253,0,0,8612,"{'noseX': 381.07, 'noseY': 298.49, 'topY': 161...",41.85,6,24,data/all-exp-separados/dataframe_blink_13.csv,"[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False, Fal..."
254,0,0,8644,"{'noseX': 377.21, 'noseY': 297.19, 'topY': 160...",40.99,6,24,data/all-exp-separados/dataframe_blink_13.csv,"[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False, Fal..."
255,0,0,8677,"{'noseX': 372.89, 'noseY': 297.15, 'topY': 160...",40.06,6,24,data/all-exp-separados/dataframe_blink_13.csv,"[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False, Fal..."

In [5]:
df_webgazer["isBlinkByEar"].apply(lambda x: len(x)).head()

0    18
1    18
2    18
3    18
4    18
Name: isBlinkByEar, dtype: int64

In [6]:
df_webgazer["Blink_sample"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[0]==True))
df_webgazer["Blink_sample1"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[1]==True))
df_webgazer["Blink_sample2"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[2]==True))
df_webgazer["Blink_sample3"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[3]==True))
df_webgazer["Blink_sample4"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[4]==True))
df_webgazer["Blink_sample5"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[5]==True))
df_webgazer["Blink_sample6"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[6]==True))
df_webgazer["Blink_sample7"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[7]==True))
df_webgazer["Blink_sample8"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[8]==True))
df_webgazer["Blink_sample9"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[9]==True))
df_webgazer["Blink_sample10"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[10]==True))
df_webgazer["Blink_sample11"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[12]==True))
df_webgazer["Blink_sample12"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[13]==True))
df_webgazer["Blink_sample13"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[13]==True))
df_webgazer["Blink_sample14"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[14]==True))
df_webgazer["Blink_sample15"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[15]==True))
df_webgazer["Blink_sample16"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[16]==True))
df_webgazer["Blink_sample17"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[17]==True))

In [8]:
df_webgazer.head()

,x,y,t,importantKeypoints,dz,trial,experiment,file_name,isBlinkByEar,isBlinkByDistance,...,Blink_sample8,Blink_sample9,Blink_sample10,Blink_sample11,Blink_sample12,Blink_sample13,Blink_sample14,Blink_sample15,Blink_sample16,Blink_sample17
0,0,0,6,"{'noseX': 299.44, 'noseY': 285.45, 'topY': 174...",59.37,1,0,data/all-exp-separados/dataframe_blink_22.csv,"[False, False, False, False, True, True, True,...","[False, False, False, False, False, False, Fal...",...,1,1,1,1,1,1,1,1,1,1
1,0,0,40,"{'noseX': 299.86, 'noseY': 284.82, 'topY': 174...",56.06,1,0,data/all-exp-separados/dataframe_blink_22.csv,"[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False, Fal...",...,0,0,0,0,0,0,1,1,1,1
2,0,0,74,"{'noseX': 300.63, 'noseY': 285.45, 'topY': 173...",53.35,1,0,data/all-exp-separados/dataframe_blink_22.csv,"[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False, Fal...",...,0,0,0,0,0,0,0,0,0,1
3,0,0,106,"{'noseX': 301.08, 'noseY': 285.31, 'topY': 173...",51.42,1,0,data/all-exp-separados/dataframe_blink_22.csv,"[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False, Fal...",...,0,0,0,0,0,0,0,0,0,0
4,0,0,141,"{'noseX': 301.66, 'noseY': 285.31, 'topY': 173...",50.71,1,0,data/all-exp-separados/dataframe_blink_22.csv,"[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False, Fal...",...,0,0,0,0,0,0,0,0,0,0

In [7]:
## Resultados por trial y persona

df_webgazer["Blink_sample0_diff"] = (df_webgazer['Blink_sample'].shift(1)+1 == df_webgazer['Blink_sample'])
df_webgazer["Blink_sample1_diff"] = (df_webgazer['Blink_sample1'].shift(1)+1 == df_webgazer['Blink_sample1'])
df_webgazer["Blink_sample2_diff"] = (df_webgazer['Blink_sample2'].shift(1)+1 == df_webgazer['Blink_sample2'])
df_webgazer["Blink_sample3_diff"] = (df_webgazer['Blink_sample3'].shift(1)+1 == df_webgazer['Blink_sample3'])
df_webgazer["Blink_sample4_diff"] = (df_webgazer['Blink_sample4'].shift(1)+1 == df_webgazer['Blink_sample4'])
df_webgazer["Blink_sample5_diff"] = (df_webgazer['Blink_sample5'].shift(1)+1 == df_webgazer['Blink_sample5'])
df_webgazer["Blink_sample6_diff"] = (df_webgazer['Blink_sample6'].shift(1)+1 == df_webgazer['Blink_sample6'])
df_webgazer["Blink_sample7_diff"] = (df_webgazer['Blink_sample7'].shift(1)+1 == df_webgazer['Blink_sample7'])
df_webgazer["Blink_sample8_diff"] = (df_webgazer['Blink_sample8'].shift(1)+1 == df_webgazer['Blink_sample8'])
df_webgazer["Blink_sample9_diff"] = (df_webgazer['Blink_sample9'].shift(1)+1 == df_webgazer['Blink_sample9'])
df_webgazer["Blink_sample10_diff"] = (df_webgazer['Blink_sample10'].shift(1)+1 == df_webgazer['Blink_sample10'])
df_webgazer["Blink_sample11_diff"] = (df_webgazer['Blink_sample11'].shift(1)+1 == df_webgazer['Blink_sample11'])
df_webgazer["Blink_sample12_diff"] = (df_webgazer['Blink_sample12'].shift(1)+1 == df_webgazer['Blink_sample12'])
df_webgazer["Blink_sample13_diff"] = (df_webgazer['Blink_sample13'].shift(1)+1 == df_webgazer['Blink_sample13'])
df_webgazer["Blink_sample14_diff"] = (df_webgazer['Blink_sample14'].shift(1)+1 == df_webgazer['Blink_sample14'])
df_webgazer["Blink_sample15_diff"] = (df_webgazer['Blink_sample15'].shift(1)+1 == df_webgazer['Blink_sample15'])
df_webgazer["Blink_sample16_diff"] = (df_webgazer['Blink_sample16'].shift(1)+1 == df_webgazer['Blink_sample16'])
df_webgazer["Blink_sample17_diff"] = (df_webgazer['Blink_sample17'].shift(1)+1 == df_webgazer['Blink_sample17'])

results = []
for x in range(0,18):
    tmp_result = df_webgazer.groupby(['trial', 'file_name'])['Blink_sample' + str(x) + '_diff'].sum().reset_index()
    #tmp_result['sample'] = x
    results.append(tmp_result)

cleaned_results = [results[0]] + [df.drop(columns=['trial', 'file_name']) for df in results[1:]]
result = pd.concat(cleaned_results, axis=1)
result

,trial,file_name,Blink_sample0_diff,Blink_sample1_diff,Blink_sample2_diff,Blink_sample3_diff,Blink_sample4_diff,Blink_sample5_diff,Blink_sample6_diff,Blink_sample7_diff,Blink_sample8_diff,Blink_sample9_diff,Blink_sample10_diff,Blink_sample11_diff,Blink_sample12_diff,Blink_sample13_diff,Blink_sample14_diff,Blink_sample15_diff,Blink_sample16_diff,Blink_sample17_diff
0,1,data/all-exp-separados/dataframe_blink_1.csv,0,0,0,0,2,14,13,10,10,10,10,10,10,10,10,10,10,10
1,1,data/all-exp-separados/dataframe_blink_10.csv,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,1,data/all-exp-separados/dataframe_blink_11.csv,0,0,6,10,10,10,10,10,10,10,10,10,10,10,10,10,9,15
3,1,data/all-exp-separados/dataframe_blink_12.csv,0,0,0,0,0,1,2,8,8,9,10,12,13,13,13,13,10,12
4,1,data/all-exp-separados/dataframe_blink_13.csv,0,0,0,0,0,5,6,7,8,10,12,12,12,12,12,12,12,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,6,data/all-exp-separados/dataframe_blink_5.csv,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0
146,6,data/all-exp-separados/dataframe_blink_6.csv,0,0,7,11,10,10,10,10,10,10,10,12,12,12,9,11,6,7
147,6,data/all-exp-separados/dataframe_blink_7.csv,0,0,0,0,0,0,0,5,7,11,12,10,13,13,18,15,15,8
148,6,data/all-exp-separados/dataframe_blink_8.csv,0,0,0,0,0,0,0,3,7,10,15,17,21,21,20,21,14,12
149,6,data/all-exp-separados/dataframe_blink_9.csv,0,0,8,10,14,15,14,15,14,14,15,13,13,13,10,9,4,2

In [17]:
threshold_columns

['Blink_sample0_diff',
 'Blink_sample1_diff',
 'Blink_sample2_diff',
 'Blink_sample3_diff',
 'Blink_sample4_diff',
 'Blink_sample5_diff',
 'Blink_sample6_diff',
 'Blink_sample7_diff',
 'Blink_sample8_diff',
 'Blink_sample9_diff',
 'Blink_sample10_diff',
 'Blink_sample11_diff',
 'Blink_sample12_diff',
 'Blink_sample13_diff',
 'Blink_sample14_diff',
 'Blink_sample15_diff',
 'Blink_sample16_diff',
 'Blink_sample17_diff']

In [16]:
threshold_columns = [col for col in result.columns if col not in ['trial', 'file_name', 'should_be']]
result['should_be'] = result['trial'].apply(lambda x: 2 if x == 3 else 10)
result[result['trial']==3]

,trial,file_name,Blink_sample0_diff,Blink_sample1_diff,Blink_sample2_diff,Blink_sample3_diff,Blink_sample4_diff,Blink_sample5_diff,Blink_sample6_diff,Blink_sample7_diff,...,Blink_sample9_diff,Blink_sample10_diff,Blink_sample11_diff,Blink_sample12_diff,Blink_sample13_diff,Blink_sample14_diff,Blink_sample15_diff,Blink_sample16_diff,Blink_sample17_diff,should_be
50,3,data/all-exp-separados/dataframe_blink_1.csv,0,0,0,0,13,11,10,10,...,10,10,10,10,10,10,10,10,11,2
51,3,data/all-exp-separados/dataframe_blink_10.csv,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
52,3,data/all-exp-separados/dataframe_blink_11.csv,0,0,0,15,2,2,2,2,...,2,2,2,2,2,2,2,13,26,2
53,3,data/all-exp-separados/dataframe_blink_12.csv,0,0,0,0,0,0,0,0,...,0,0,10,7,7,7,3,2,2,2
54,3,data/all-exp-separados/dataframe_blink_13.csv,0,0,0,0,0,0,0,6,...,3,2,4,4,4,4,4,4,4,2
55,3,data/all-exp-separados/dataframe_blink_14.csv,0,0,0,0,2,4,9,3,...,5,3,3,2,2,2,2,2,2,2
56,3,data/all-exp-separados/dataframe_blink_15.csv,0,0,0,9,3,2,2,2,...,2,2,2,2,2,2,5,3,3,2
57,3,data/all-exp-separados/dataframe_blink_16.csv,0,0,0,0,21,3,3,2,...,2,2,2,2,2,2,2,2,5,2
58,3,data/all-exp-separados/dataframe_blink_17.csv,0,0,0,0,0,0,0,4,...,2,2,3,3,3,3,3,2,2,2
59,3,data/all-exp-separados/dataframe_blink_18.csv,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
60,3,data/all-exp-separados/dataframe_blink_19.csv,0,0,0,0,0,0,0,3,...,2,2,2,2,2,2,2,2,2,2
61,3,data/all-exp-separados/dataframe_blink_2.csv,0,0,1,11,8,5,6,7,...,5,5,5,5,5,10,9,9,0,2
62,3,data/all-exp-separados/dataframe_blink_20.csv,0,0,0,0,0,0,0,2,...,4,4,2,2,2,2,2,2,2,2
63,3,data/all-exp-separados/dataframe_blink_21.csv,0,0,0,0,0,1,4,7,...,9,9,3,3,3,2,2,2,2,2
64,3,data/all-exp-separados/dataframe_blink_22.csv,0,0,0,2,2,2,2,2,...,2,2,2,2,2,2,2,7,21,2
65,3,data/all-exp-separados/dataframe_blink_23.csv,0,0,2,16,2,2,2,2,...,2,2,2,2,2,2,3,0,0,2
66,3,data/all-exp-separados/dataframe_blink_24.csv,0,0,0,0,0,0,0,0,...,1,21,7,3,3,3,3,3,3,2
67,3,data/all-exp-separados/dataframe_blink_25.csv,0,0,0,0,0,0,6,6,...,2,3,2,2,2,2,2,2,4,2
68,3,data/all-exp-separados/dataframe_blink_3.csv,0,0,0,0,0,0,0,0,...,0,0,15,21,21,9,5,2,2,2
69,3,data/all-exp-separados/dataframe_blink_4.csv,0,0,0,2,13,3,2,2,...,2,2,2,2,2,2,4,13,2,2
70,3,data/all-exp-separados/dataframe_blink_5.csv,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
71,3,data/all-exp-separados/dataframe_blink_6.csv,0,0,14,9,2,2,2,2,...,2,2,2,2,2,2,4,6,3,2
72,3,data/all-exp-separados/dataframe_blink_7.csv,0,0,0,0,0,8,12,6,...,6,5,3,3,3,5,6,15,10,2
73,3,data/all-exp-separados/dataframe_blink_8.csv,0,0,0,0,0,0,0,0,...,8,17,4,3,3,2,2,4,7,2
74,3,data/all-exp-separados/dataframe_blink_9.csv,0,2,10,3,2,2,2,4,...,3,5,8,4,4,2,2,0,0,2

In [21]:
THRESHOLDS = [0.15, 0.2, 0.22, 0.23, 0.25, 0.265, 0.27, 0.285,
                 0.29, 0.3, 0.31, 0.33, 0.34, 0.35, 0.36, 0.37, 0.39, 0.4]


results_global = []

for i, threshold in enumerate(threshold_columns):
    preds = result[threshold]
    truth = result['should_be']
    mae = np.mean(np.abs(preds - truth))
    rmse = np.sqrt(np.mean((preds - truth) ** 2))
    results_global.append({'Threshold': THRESHOLDS[i], 'Error Absoluto Medio': mae, 'Error Cuadrático Medio': rmse})

results_global_df = pd.DataFrame(results_global).sort_values(by='Error Cuadrático Medio')

results_global_df

    Threshold  Error Absoluto Medio  Error Cuadrático Medio
14      0.360              2.806667                4.593474
11      0.330              2.806667                4.725110
13      0.350              2.786667                4.753946
12      0.340              2.786667                4.753946
15      0.370              3.000000                4.835976
9       0.300              3.320000                5.200000
8       0.290              3.566667                5.255473
7       0.285              3.880000                5.502727
10      0.310              3.333333                5.536545
6       0.270              4.726667                6.299735
5       0.265              4.900000                6.478168
4       0.250              5.806667                7.278736
17      0.400              5.433333                7.563509
16      0.390              4.566667                7.957805
3       0.230              6.986667                8.088675
2       0.220              7.360000                8.289753
1       0.200              8.586667                9.103113
0       0.150              8.666667                9.165151

In [1]:
# Calcular MAE y RMSE por threshold
results = []
metodo = "EAR"
plt.style.use('bmh')
THRESHOLDS = [0.15, 0.2, 0.22, 0.23, 0.25, 0.265, 0.27, 0.285,
                 0.29, 0.3, 0.31, 0.33, 0.34, 0.35, 0.36, 0.37, 0.39, 0.4]
for i, threshold in enumerate(threshold_columns):
    preds = result[threshold]
    truth = result['should_be']
    mae = np.mean(np.abs(preds - truth))
    rmse = np.sqrt(np.mean((preds - truth) ** 2))
    results.append({
        'Threshold': threshold,
        'Threshold_float': float(str(THRESHOLDS[i]).replace(",", ".").replace(" ", "")),
        'MAE': mae,
        'RMSE': rmse
    })

results_df = pd.DataFrame(results).sort_values('Threshold_float')

# Graficar
plt.figure(figsize=(12, 6))
plt.plot(results_df['Threshold_float'], results_df['MAE'], label='EAM', marker='o')
plt.plot(results_df['Threshold_float'], results_df['RMSE'], label='ECM', marker='s')
plt.xlabel("Threshold")
plt.ylabel("Error")
plt.axvline(0.36, color="red", linestyle="--", lw=1)
plt.title(metodo + " Error (EAM y ECM) vs. Threshold")
plt.legend()
plt.grid(True)
plt.show()

NameError: name 'plt' is not defined