In [13]:
import pandas as pd
import numpy as np
import blinksear as ear
import blinksdistance as distance
import blinkscolors as colors
import json
import matplotlib.pyplot as plt
from pathlib import Path

from blinksear import isBlinkByEar
from blinksdistance import BlinkDistance
from blinkscolors import Colors
from blinkscorrelation import Correlation

In [14]:
def generate_webgazer_dataframe(df):
    df_webgazer = df[~df["webgazer_data"].isna()]
    dfs = []
    for row in range(len(df_webgazer)):
        data_list = json.loads(df_webgazer["webgazer_data"].iloc[row])
        df_tmp = pd.DataFrame(data_list)
        df_tmp["trial"] = row + 1
        dfs.append(df_tmp)
    return pd.concat(dfs)

In [9]:
# This can load all data but is not storing df_webgazer in any place
files = Path("./data").glob("*.csv")
dfs = []
i = 0
for file in files:
    if "blink" in str(file):
        if "7" in str(file):
          print(file)
          df = pd.read_csv(file)
          df_tmp = generate_webgazer_dataframe(df)
          print(len(df_tmp))
          df_tmp["experiment"] = i
          i+=1
          dfs.append(df_tmp)

df_webgazer = pd.concat(dfs)
print(len(df_webgazer))

data/blink-experiment-7.csv
1923
1923

In [10]:
blinkDistance = distance.BlinkDistance()
blinkColors = Colors()
blinkCorrelations = Correlation()


df_webgazer["isBlinkByEar"] = df_webgazer["importantKeypoints"].map(
    lambda x: isBlinkByEar(
        x["rightEyeTopArc"],
        x["rightEyeBottomArc"],
        x["leftEyeTopArc"],
        x["leftEyeBottomArc"],
    )
)
df_webgazer["isBlinkByDistance"] = df_webgazer["importantKeypoints"].map(
    lambda x: blinkDistance.isBlinkByDistance(
        x["rightEyeTopArc"],
        x["rightEyeBottomArc"],
        x["leftEyeTopArc"],
        x["leftEyeBottomArc"],
    )
)
df_webgazer["isBlinkColors"] = df_webgazer.apply(
    lambda row: blinkColors.isBlinkByColors(
        list(row["leftEye"]["data"].values()), list(row["rightEye"]["data"].values())
    ),
    axis=1,
)


df_webgazer["isBlinkByCorrelation"] = df_webgazer.apply(
    lambda row: blinkCorrelations.isBlinkByCorrelation(
        list(row["leftEye"]["data"].values()), list(row["rightEye"]["data"].values())
    ),
    axis=1,
)


# df_webgazer['isBlinkByEar'] = df_webgazer['importantKeypoints'].map(lambda x: isBlinkByEar(x['rightEyeTopArc'], x['rightEyeBottomArc'], x['leftEyeTopArc'], x['leftEyeBottomArc']))

df_webgazer

,x,y,t,importantKeypoints,leftEye,rightEye,dz,trial,experiment,isBlinkByEar,isBlinkByDistance,isBlinkColors,isBlinkByCorrelation
0,0,0,63,"{'noseX': 336.93, 'noseY': 310.7, 'topY': 175....","{'data': {'0': 67, '1': 52, '2': 36, '3': 255,...","{'data': {'0': 80, '1': 62, '2': 45, '3': 255,...",45.36,1,0,"[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False]","[False, False, False, False, False, False]","[False, False, False, False, False, False]"
1,0,0,79,"{'noseX': 336.49, 'noseY': 310.09, 'topY': 175...","{'data': {'0': 64, '1': 47, '2': 27, '3': 255,...","{'data': {'0': 100, '1': 72, '2': 50, '3': 255...",44.63,1,0,"[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False]","[False, False, False, False, False, False]","[False, False, False, False, False, False]"
2,0,0,108,"{'noseX': 335.7, 'noseY': 310.49, 'topY': 175....","{'data': {'0': 64, '1': 48, '2': 31, '3': 255,...","{'data': {'0': 107, '1': 76, '2': 55, '3': 255...",44.40,1,0,"[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False]","[False, False, False, False, False, False]","[False, False, False, False, False, False]"
3,0,0,141,"{'noseX': 336.59, 'noseY': 309.75, 'topY': 175...","{'data': {'0': 61, '1': 47, '2': 29, '3': 255,...","{'data': {'0': 105, '1': 73, '2': 52, '3': 255...",44.64,1,0,"[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False]","[False, False, False, False, False, False]","[False, False, False, False, False, False]"
4,0,0,176,"{'noseX': 336.23, 'noseY': 310.56, 'topY': 175...","{'data': {'0': 63, '1': 46, '2': 27, '3': 255,...","{'data': {'0': 98, '1': 68, '2': 46, '3': 255,...",44.45,1,0,"[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False]","[False, False, False, False, False, False]","[False, False, False, False, False, False]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,0,0,12416,"{'noseX': 324.29, 'noseY': 314.29, 'topY': 183...","{'data': {'0': 60, '1': 46, '2': 25, '3': 255,...","{'data': {'0': 105, '1': 73, '2': 53, '3': 255...",42.48,6,0,"[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False]","[False, False, False, False, False, False]","[False, False, False, False, False, False]"
366,0,0,12447,"{'noseX': 325.56, 'noseY': 314.51, 'topY': 182...","{'data': {'0': 61, '1': 46, '2': 29, '3': 255,...","{'data': {'0': 103, '1': 74, '2': 57, '3': 255...",42.03,6,0,"[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False]","[False, True, False, False, False, True]","[False, True, False, False, False, True]"
367,0,0,12481,"{'noseX': 325.67, 'noseY': 313.72, 'topY': 182...","{'data': {'0': 57, '1': 44, '2': 29, '3': 255,...","{'data': {'0': 104, '1': 76, '2': 52, '3': 255...",42.39,6,0,"[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False]","[False, False, False, False, False, False]","[False, False, False, False, False, False]"
368,0,0,12517,"{'noseX': 326.86, 'noseY': 313.75, 'topY': 182...","{'data': {'0': 61, '1': 48, '2': 29, '3': 255,...","{'data': {'0': 102, '1': 74, '2': 57, '3': 255...",42.58,6,0,"[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False]","[False, False, False, False, False, False]","[False, False, False, False, False, False]"
369,0,0,12551,"{'noseX': 327.52, 'noseY': 313.6, 'topY': 182....","{'data': {'0': 58, '1': 44, '2': 29, '3': 255,...","{'data': {'0': 103, '1': 76, '2': 54, '3': 255...",41.09,6,0,"[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False]","[False, False, False, False, False, False]","[False, True, False, False, False, True]"

In [11]:
df_webgazer["Blink_sample"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[0]==True))
df_webgazer["Blink_sample1"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[1]==True)+1)
df_webgazer["Blink_sample2"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[2]==True)+2)
df_webgazer["Blink_sample3"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[3]==True)+3)
df_webgazer["Blink_sample4"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[4]==True)+4)
df_webgazer["Blink_sample5"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[5]==True)+5)
df_webgazer["Blink_sample6"] = df_webgazer["isBlinkByEar"].apply(lambda x: int(x[6]==True)+6)

In [12]:
df_webgazer

,x,y,t,importantKeypoints,leftEye,rightEye,dz,trial,experiment,isBlinkByEar,...,isBlinkColors,isBlinkByCorrelation,Blink_sample,Blink_sample1,Blink_sample2,Blink_sample3,Blink_sample4,Blink_sample5,Blink_sample6,Blink_sample3_diff
0,0,0,62,"{'noseX': 288.29, 'noseY': 313.05, 'topY': 190...","{'data': {'0': 84, '1': 62, '2': 42, '3': 255,...","{'data': {'0': 144, '1': 105, '2': 82, '3': 25...",51.57,1,0,"[False, False, False, False, False, False, Fal...",...,"[False, False, False, False, False, False]","[False, False, False, False, False, False]",0,1,2,3,4,5,6,False
1,0,0,81,"{'noseX': 289.14, 'noseY': 313.56, 'topY': 190...","{'data': {'0': 44, '1': 30, '2': 15, '3': 255,...","{'data': {'0': 66, '1': 41, '2': 27, '3': 255,...",52.57,1,0,"[False, False, False, False, False, False, Fal...",...,"[False, False, False, False, False, False]","[False, False, False, False, False, False]",0,1,2,3,4,5,6,False
2,0,0,106,"{'noseX': 289.29, 'noseY': 313.86, 'topY': 190...","{'data': {'0': 46, '1': 31, '2': 15, '3': 255,...","{'data': {'0': 66, '1': 43, '2': 26, '3': 255,...",53.01,1,0,"[False, False, False, False, False, False, Fal...",...,"[False, False, False, False, False, False]","[False, False, False, False, False, False]",0,1,2,3,4,5,6,False
3,0,0,142,"{'noseX': 288.98, 'noseY': 313.11, 'topY': 190...","{'data': {'0': 46, '1': 31, '2': 15, '3': 255,...","{'data': {'0': 64, '1': 42, '2': 25, '3': 255,...",50.86,1,0,"[False, False, False, False, False, False, Fal...",...,"[False, False, False, False, False, False]","[False, False, False, False, False, False]",0,1,2,3,4,5,6,False
4,0,0,175,"{'noseX': 289.17, 'noseY': 313.61, 'topY': 190...","{'data': {'0': 48, '1': 32, '2': 16, '3': 255,...","{'data': {'0': 67, '1': 42, '2': 27, '3': 255,...",52.18,1,0,"[False, False, False, False, False, False, Fal...",...,"[False, False, False, False, False, False]","[False, False, False, False, False, False]",0,1,2,3,4,5,6,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,0,0,7584,"{'noseX': 361.32, 'noseY': 259.74, 'topY': 173...","{'data': {'0': 60, '1': 46, '2': 34, '3': 255,...","{'data': {'0': 69, '1': 53, '2': 36, '3': 255,...",66.11,6,4,"[False, False, False, False, False, False, Fal...",...,"[False, False, False, False, False, False]","[False, False, False, False, False, False]",0,1,2,3,4,5,6,False
224,0,0,7622,"{'noseX': 361.16, 'noseY': 259.39, 'topY': 173...","{'data': {'0': 60, '1': 47, '2': 32, '3': 255,...","{'data': {'0': 70, '1': 52, '2': 36, '3': 255,...",65.16,6,4,"[False, False, False, False, False, False, Fal...",...,"[False, False, False, False, False, False]","[False, False, False, False, False, False]",0,1,2,3,4,5,6,False
225,0,0,7653,"{'noseX': 361.02, 'noseY': 259.52, 'topY': 173...","{'data': {'0': 60, '1': 47, '2': 30, '3': 255,...","{'data': {'0': 67, '1': 52, '2': 35, '3': 255,...",66.11,6,4,"[False, False, False, False, False, False, Fal...",...,"[False, False, False, False, False, False]","[False, False, False, False, False, False]",0,1,2,3,4,5,6,False
226,0,0,7687,"{'noseX': 361.42, 'noseY': 259.34, 'topY': 173...","{'data': {'0': 60, '1': 44, '2': 34, '3': 255,...","{'data': {'0': 66, '1': 51, '2': 33, '3': 255,...",64.75,6,4,"[False, False, False, False, False, False, Fal...",...,"[False, False, False, False, False, False]","[False, False, False, False, False, False]",0,1,2,3,4,5,6,False
227,0,0,7720,"{'noseX': 360.66, 'noseY': 259.4, 'topY': 173....","{'data': {'0': 59, '1': 47, '2': 34, '3': 255,...","{'data': {'0': 68, '1': 50, '2': 33, '3': 255,...",65.69,6,4,"[False, False, False, False, False, False, Fal...",...,"[False, False, False, False, False, False]","[False, False, False, False, False, False]",0,1,2,3,4,5,6,False

In [12]:
df_webgazer["Blink_sample0_diff"] = (df_webgazer['Blink_sample'].shift(1)+1 == df_webgazer['Blink_sample'])
df_webgazer["Blink_sample1_diff"] = (df_webgazer['Blink_sample1'].shift(1)+1 == df_webgazer['Blink_sample1'])
df_webgazer["Blink_sample2_diff"] = (df_webgazer['Blink_sample2'].shift(1)+1 == df_webgazer['Blink_sample2'])
df_webgazer["Blink_sample3_diff"] = (df_webgazer['Blink_sample3'].shift(1)+1 == df_webgazer['Blink_sample3'])
df_webgazer["Blink_sample4_diff"] = (df_webgazer['Blink_sample4'].shift(1)+1 == df_webgazer['Blink_sample4'])
df_webgazer["Blink_sample5_diff"] = (df_webgazer['Blink_sample5'].shift(1)+1 == df_webgazer['Blink_sample5'])
df_webgazer["Blink_sample6_diff"] = (df_webgazer['Blink_sample6'].shift(1)+1 == df_webgazer['Blink_sample6'])

results = []
for x in range(0,7):
    tmp_result = df_webgazer.groupby('trial')['Blink_sample' + str(x) + '_diff'].sum().reset_index()
    #tmp_result['sample'] = x
    results.append(tmp_result)

result = pd.concat(results, axis=1, join='inner')
result

,trial,Blink_sample0_diff,trial,Blink_sample1_diff,trial,Blink_sample2_diff,trial,Blink_sample3_diff,trial,Blink_sample4_diff,trial,Blink_sample5_diff,trial,Blink_sample6_diff
0,1,0,1,0,1,0,1,0,1,0,1,11,1,10
1,2,0,2,0,2,0,2,0,2,0,2,10,2,10
2,3,0,3,0,3,0,3,0,3,0,3,4,3,2
3,4,0,4,0,4,0,4,0,4,0,4,11,4,11
4,5,0,5,0,5,0,5,0,5,0,5,10,5,10
5,6,0,6,0,6,0,6,0,6,5,6,12,6,11

In [43]:
df_webgazer.groupby('trial')['Blink_sample6_diff'].sum().reset_index()

   trial  Blink_sample6_diff
0      1                  43
1      2                  50
2      3                  10
3      4                  51
4      5                  51
5      6                  58